### ISSUE TITLE
include open gl after defining gl_silence_deprecation

### ISSUE THREAD

**Issue by bitwitch** [MumflrFumperdink/olcPGEMac#1]
hey thanks for the mac port! when i compiled using make i noticed all the opengl deprecation warnings (fuck you apple). I just had to move the include for OpenGL, in olcPixelEngine.h line 207, below where GL_SILENCE_DEPRECATION is defined. 

I would submit a PR myself, but I kind of hate how people change one single line and then are considered a 'contributor'.

**Comment by MumflrFumperdink** [comment]
Hey, thanks for telling me! This problem did not happen to me and the order did not seem to matter on my computer at least, so I switched the order for you.
