### ISSUE TITLE
Compatibility with ImGui and/or port to GLFW3

### ISSUE THREAD

**Issue by johnmarianhoffman** [MumflrFumperdink/olcPGEMac#13]
It appears there's an issue rendering "Dear ImGui" overlays (https://github.com/ocornut/imgui and dandistine's integration with olcPGE https://github.com/dandistine/olcPGEDearImGui) that seems to be related to the use of GLUT.  Dear ImGui's example using GLUT ALSO fails, so it's clearly not your code!  The GLFW3 imgui example code works fine though.  

Before I started playing around with trying to implement using GLFW, I wanted to check and see if there were a reason you had used GLUT over GLFW, and/or if there were any plans to eventually do a GLFW port?

Thanks for all your work!  This seems like more of an issue for imgui, however given the scale of their work I figure it's probably easier and faster to just do a quick extension of OLC to use gflw or glut.

Edits: spelling, missing words, apologies for any others that I didn't catch!

**Comment by MumflrFumperdink** [comment]
Hey, no problem! I'm not familiar with "Dear ImGui", but the reason I used GLUT was that it already comes installed in a mac once you install developer tools. I wanted to fit the simplicity of the PGE, which meant trying to fit it all into one file with as few external libraries as possible for an easy installation.

I have not used GLFW before, so if you think that it will do a better job, then go ahead. If you do decide to follow through, let me know how it goes!

**Comment by johnmarianhoffman** [comment]
Ah yeah.  I completely agree.  I forgot the glfw doesn't come preinstalled on macs!  Makes perfect sense.  

I'll see if I can't locate where this issues is specifically arising first.  It's possible that it's coming from the imgui integration with PGE, but given that it also occurs in the imgui+glut example code (completely independent of PGE) makes me suspect it's a GLUT/OpenGL viewport issue.  

I'll let you know how it goes!

**Comment by johnmarianhoffman** [comment]
Just wanted to provide a quick update:

I went ahead and added GLFW3 directly to the engine alongside GLUT, so one can select their desired platform on Mac.  I think there is interest in providing a cross-platform GLFW version of the engine eventually too, so maybe this will generate some discussion.  Right now just just gives mac users an extra option.

Thanks again for being so quick to respond!  Check it out sometime if you get a chance. :D 

https://github.com/OneLoneCoder/olcPixelGameEngine/pull/172
https://github.com/johnmarianhoffman/olcPixelGameEngine/tree/glfw_conversion
