### ISSUE TITLE
I really need your help!

### ISSUE THREAD

**Issue by egetunadiken** [MumflrFumperdink/olcPGEMac#15]
**PLEASE CHECK COMMENTS!!!**

I have done everything, the makefile is working, I can see the colored screen...

I have XCode downloaded and that's okay as well.

$ cd olcPGEMac
$ sudo ./setup.sh

This part I don't understand. What folder should my setup.sh be in? And where should that folder be located? I've tried placing it in Library/Developer/Xcode/Templates but it doesn't work. I've done literally everything you can imagine. I've even downloaded the seperate file and placed it in literally every folder. 

Please guide me. I'm a young coder using this for a school project. I really need your help.

**Comment by egetunadiken** [comment]
Update: I'm now able to run the colored screen in XCode so I think I've successfully managed to install (the template is opening as well!) however my code won't compile because I want the extension 2D file as well. I've inclueded it in the header but no can do... This is my main:



#include "olcPGEX_Graphics2D.h"
#include "olcPixelGameEngine.h"
#include "vector"


using namespace std;

double distance(double x1, double y1, double x2, double y2)
{
    return sqrt(pow(x1 - x2, 2) + pow(y1 - y2, 2));
}

struct Tile {
    bool IsFull;
    double x, y;
    Tile(int xIn, int yIn) :x(xIn), y(yIn), IsFull(false) {};
};

struct Peashooter {
    double x, y;
    double HP;
    double attackCD, attackRate;

    Peashooter(double xIn, double yIn, double HPIn):attackCD(0),attackRate(3) {
        x = xIn;
        y = yIn;
        HP = HPIn;
    }
};

struct Sunflower {
    double x, y;
    double HP;
    double sunCD, sunRate;

    Sunflower(double xIn, double yIn, double HPIn, double sunRateIn) {
        x = xIn;
        y = yIn;
        HP = HPIn;
        sunCD = 3;
        sunRate =sunRateIn ;
    }
};

struct Sun {
    double x, y;
    int sungain;
    Sun(double xIn, double yIn) :x(xIn), y(yIn), sungain(50) {};
};

struct Zombie {

    double x, y;
    double HP;
    double speed;
    double attackCD, attackRate;
    double damage;

    Zombie(double xIn, double yIn, double HPIn, double speedIn, double attackRateIn) {
    
        x = xIn;
        y = yIn;
        HP = HPIn;
        speed = speedIn;
        attackCD = 0;
        attackRate = attackRateIn;
        damage = 40;

    };
};

struct Card{
    double x, y;
    bool IsSelected;
    Card(double xIn, double yIn) :x(xIn), y(yIn) {
        IsSelected = false;
    };
};

struct Seed {
    double x, y;
    double speed;
    double damage;
    Seed(double xIn, double yIn, double damageIn) : x(xIn), y(yIn), damage(damageIn), speed(50) {};
};




class PlantsGame: public olc::PixelGameEngine {

    double gameTime;
    bool gameEnd;
    bool gamePause;

    bool AnyCardSelected;
    int CurrentSun;
    
    vector<Sun*> Suns;
    vector<Sunflower*> Sunflowers;
    vector <Peashooter*> Peashooters;
    vector <Seed*> Seeds;
    vector<Zombie*> Zombies;
    vector<Tile*> Tiles;
    vector<Card*> Cards;

    
    
    olc::Sprite* zombieSprite;
    olc::Sprite* sunflowerSprite;
    olc::Sprite* peashooterSprite;
    olc::Sprite* sunSprite;
    olc::Sprite* seedSprite;

    
    float spawnCD , spawnRate; //Zombie spawn timers

    int sunflowerCost,peashooterCost;

public:
    bool OnUserCreate() //override
    {
        gameTime = 0;
        gameEnd = false;
        gamePause = false;

        //Create Tiles
        for (int i = 1; i <= 6; i++)
        {
            for (int j = 1; j <= 4; j++)
            {
                Tiles.push_back(new Tile((i-1)*50, j  * 50));
            }

        }
        //Create Tiles
        
        //Create Cards
        Cards.push_back(new Card (0,0));
        Cards.push_back(new Card (50, 0));
        //Create Cards

        //Initialization for zombies
        spawnCD = 3;
        spawnRate = 5;
        zombieSprite = new olc::Sprite("Sprites/zombie1.png");
        //Initialization for zombies

        seedSprite = new olc::Sprite("Sprites/seed.png");
        sunSprite =new olc::Sprite("Sprites/sun1.png");
        peashooterSprite =new olc::Sprite("Sprites/peashooter1.png");
        sunflowerSprite =new olc::Sprite("Sprites/sunflower1.png");
        CurrentSun = 100;
        sunflowerCost = 50;
        peashooterCost = 100;

        return true;
    }

    bool OnUserUpdate(float fElapsedTime) //override
    {
        gameTime += fElapsedTime;

        //GAME END SCREEN
        if (gameEnd) {
            Clear(olc::BLACK);
            DrawString(110, 10, "GAME OVER", olc::WHITE);

            FillRect(100, 90, 100, 50, olc::DARK_GREEN);
            DrawString(110, 110, "PLAY AGAIN", olc::WHITE);
            FillRect(100, 150, 100, 50, olc::DARK_RED);
            DrawString(135, 170, "EXIT", olc::WHITE);
            SetPixelMode(olc::Pixel::ALPHA);
            if (GetMouseX() >= 100 && GetMouseX() <= 200 && GetMouseY() >= 90 && GetMouseY() <= 140)
            {
                FillRect(100, 90, 100, 50, olc::WHITE);
                DrawString(110, 110, "PLAY AGAIN", olc::DARK_GREEN);

                if (GetMouse(0).bReleased)
                {
                    OnUserCreate();

                }
            }
            if (GetMouseX() >= 100 && GetMouseX() <= 200 && GetMouseY() >= 150 && GetMouseY() <= 200)
            {
                FillRect(100, 150, 100, 50, olc::WHITE);
                DrawString(135, 170, "EXIT", olc::DARK_RED);

                if (GetMouse(0).bReleased)
                {
                    delete zombieSprite;
                    delete seedSprite;
                    delete sunSprite;
                    delete peashooterSprite;
                    delete sunflowerSprite;

                    return false;
                }
            }

            return true;
        }
        //GAME END SCREEN


        //GAME PAUSE
        if (GetKey(olc::Key::P).bPressed) {
            gamePause = true;
        }
        if (gamePause == true)
        {
            Clear(olc::BLACK);
            FillRect(100, 100, 100, 50, olc::DARK_GREEN);
            DrawString(90, 10, "PLANTS & ZOMBIES PAUSED", olc::WHITE);
            DrawString(120, 120, "CONTINUE", olc::WHITE);
            SetPixelMode(olc::Pixel::ALPHA);
            if (GetMouseX() >= 100 && GetMouseX() <= 200 && GetMouseY() >= 100 && GetMouseY() <= 150)
            {
                FillRect(100, 100, 100, 50, olc::WHITE);
                DrawString(120, 120, "CONTINUE", olc::DARK_GREEN);

                if (GetMouse(0).bReleased)
                {
                    gamePause = false;
                }
            }
            return true;

        }
        //GAME PAUSE





        //Drawing the background
        Clear(olc::DARK_GREEN);
        FillRect(0, 0, 300, 50, olc::BLACK);
        SetPixelMode(olc::Pixel::ALPHA);
        //Drawing the background

        //Drawing the tiles
        for (auto a:Tiles)
        {
            if (a->IsFull)
            {
                DrawRect(a->x, a->y, 49, 49, olc::BLACK);
            }
            else
            {
                if (GetMouseX() > a->x&& GetMouseX() < a->x + 50 && GetMouseY() > a->y&& GetMouseY() < a->y + 50)
                {
                    DrawRect(a->x, a->y, 49, 49, olc::WHITE);
                }

                else {
                    DrawRect(a->x, a->y, 49, 49, olc::VERY_DARK_GREY);
                }
            }
           
        }
        //Drawing the tiles


        //Drawing the cards
        FillRect(Cards[0]->x, Cards[0]->y, 49, 49, olc::WHITE);
        DrawSprite(Cards[0]->x, Cards[0]->y, sunflowerSprite, 1);
        DrawString(Cards[0]->x + 30, Cards[0]->y + 40, to_string(sunflowerCost) , olc::DARK_RED);

        FillRect(Cards[1]->x, Cards[1]->y, 49, 49, olc::WHITE);
        DrawSprite(Cards[1]->x , Cards[1]->y , peashooterSprite, 1);
        DrawString(Cards[1]->x + 25, Cards[1]->y + 40, to_string(peashooterCost), olc::DARK_RED);

        for (auto a:Cards)
        {
            if (a->IsSelected)
            {
                DrawRect(a->x, a->y, 49, 49, olc::RED);
            }
            else
            {
                if (GetMouseX() > a->x&& GetMouseX() < a->x + 50 && GetMouseY() > a->y&& GetMouseY() < a->y + 50)
                {
                    DrawRect(a->x, a->y, 49, 49, olc::WHITE);
                }

                else
                {
                    DrawRect(a->x, a->y, 49, 49, olc::BLACK);
                }
            }
        }
        //Drawing the cards

        //Drawing the remaining sun
        DrawSprite(ScreenWidth() - 50, 0, sunSprite, 1);
        DrawString(ScreenWidth() - 35, 40, to_string(CurrentSun), olc::WHITE);
        //Drawing the remaining sun


        //Zombie Spawns
        if (spawnCD < 0) {
            int s = rand() % Tiles.size();
            Zombies.push_back(new Zombie(ScreenWidth(), Tiles[s]->y, 100, 10, 4));
            spawnCD = spawnRate;
        }
        if (gameTime < 5) { spawnCD -= fElapsedTime; }
        else if (gameTime < 10) { spawnCD -= fElapsedTime*2; }
        else if (gameTime < 15) { spawnCD -= fElapsedTime * 3; }
        else { spawnCD -= fElapsedTime * 4; }
        //Zombie Spawns


        //Zombie Move & Attack
        for (int i = 0; i < Zombies.size(); i++) {
            Zombies[i]->attackCD -= fElapsedTime;
            bool canAttack = false;
            for (int j = 0; j < Peashooters.size(); j++) {
                if (distance(Zombies[i]->x, Zombies[i]->y, Peashooters[j]->x, Peashooters[j]->y) < 5)
                {
                    canAttack = true;
                    if (Zombies[i]->attackCD <= 0) {

                        Peashooters[j]->HP -= Zombies[i]->damage;
                        Zombies[i]->attackCD = Zombies[i]->attackRate;
                    }
                }
            }

            for (int k = 0; k < Sunflowers.size(); k++) {
                if (distance(Zombies[i]->x, Zombies[i]->y, Sunflowers[k]->x, Sunflowers[k]->y) < 5)
                {
                    canAttack = true;
                    if (Zombies[i]->attackCD <= 0) {
                        Zombies[i]->attackCD = Zombies[i]->attackRate;
                        Sunflowers[k]->HP -= Zombies[i]->damage;
                    }
                }
            }

            if (!canAttack) {
                Zombies[i]->x -= Zombies[i]->speed * fElapsedTime;
            }

        }
        //Zombie Move & Attack


        //Plants death
        for (int i = 0; i < Peashooters.size(); i++) {
            if (Peashooters[i]->HP <= 0) {

                for (auto a : Tiles) {
                    if (a->x == Peashooters[i]->x && a->y == Peashooters[i]->y) {
                        a->IsFull = false;
                    }
                }
                delete Peashooters[i];
                Peashooters.erase(Peashooters.begin() + i);
                i--;
            }
        }

        for (int i = 0; i < Sunflowers.size(); i++) {
            if (Sunflowers[i]->HP <= 0) {
                for (auto a : Tiles) {
                    if (a->x == Sunflowers[i]->x && a->y == Sunflowers[i]->y) {
                        a->IsFull = false;
                    }
                }
                Sunflowers.erase(Sunflowers.begin() + i);
                i--;
            }
        }
        //Plants death


        //Peashooter Attack
        for (int i = 0; i < Peashooters.size(); i++) {
            Peashooters[i]->attackCD -= fElapsedTime;
            if (Peashooters[i]->attackCD <= 0) {
                Seeds.push_back(new Seed(Peashooters[i]->x, Peashooters[i]->y, 30));
                Peashooters[i]->attackCD = Peashooters[i]->attackRate;
            }
        }
        //Peashooter Attack

        //Seeds Move & Attack
        for (int i = 0; i< Seeds.size();i++) {
            Seeds[i]->x += Seeds[i]->speed * fElapsedTime;
            for (int j = 0; j < Zombies.size(); j++) {
                if (distance(Seeds[i]->x, Seeds[i]->y, Zombies[j]->x, Zombies[j]->y) < 5) {
                    Zombies[j]->HP -= Seeds[i]->damage;
                    delete Seeds[i];
                    Seeds.erase(Seeds.begin() + i);
                    i--;
                    if (Zombies[j]->HP <= 0) {
                        delete Zombies[j];
                        Zombies.erase(Zombies.begin() + j);
                        j--;
                    }
                    break;


                }

            }
            
        }
        //Seeds Move & Attack

        //Seeds disappear
        for (int i = 0; i < Seeds.size(); i++) {
            if (Seeds[i]->x >= ScreenWidth()) {
                delete Seeds[i];
                Seeds.erase(Seeds.begin() + i);
                i--;
            }
        }
        //Seeds disappear

        //Sunflower Sun Creation
        for (int i = 0; i < Sunflowers.size();i++) {
            Sunflowers[i]->sunCD -= fElapsedTime;
            if (Sunflowers[i]->sunCD <= 0) {
                Sunflowers[i]->sunCD = Sunflowers[i]->sunRate;
                Suns.push_back(new Sun(Sunflowers[i]->x, Sunflowers[i]->y));
            }
        }
        //Sunflower Sun Creation


        //Mouse operations
        if (GetMouse(0).bPressed) {

            // Selecting-Deselecting Card
            
            //Deselect
            bool anyselection = false;
            for (auto a : Cards) {
                
                anyselection = anyselection || a->IsSelected;
                if (GetMouseX() > a->x&& GetMouseX() < a->x + 50 && GetMouseY() > a->y&& GetMouseY() < a->y + 50) {
                    if (a->IsSelected) { a->IsSelected = false; }
                  
                
                }
                

            }
            //Deselect

            //Select
            if (!anyselection) {
                for (auto a : Cards) {

                    if (GetMouseX() > a->x&& GetMouseX() < a->x + 50 && GetMouseY() > a->y&& GetMouseY() < a->y + 50) {
                        if (!a->IsSelected) { a->IsSelected = true; }
                    }
                }
            }
            //Select
            // Selecting-Deselecting Card



            //Planting
            for (auto a : Tiles) {
                if (GetMouseX() > a->x&& GetMouseX() < a->x + 50 && GetMouseY() > a->y&& GetMouseY() < a->y + 50) {

                    if (!a->IsFull) {

                        if (Cards[0]->IsSelected && sunflowerCost <= CurrentSun) {

                            Sunflowers.push_back(new Sunflower(a->x , a->y , 100, 5));
                            a->IsFull = true;
                            Cards[0]->IsSelected = false;
                            CurrentSun -= sunflowerCost;

                        }

                        if (Cards[1]->IsSelected && peashooterCost <= CurrentSun) {

                            Peashooters.push_back(new Peashooter(a->x , a->y, 100));
                            a->IsFull = true;
                            Cards[1]->IsSelected = false;
                            CurrentSun -= peashooterCost;
                        }
                    }
                }
            }
            //Planting


            //Collecting Sun
            for (int i = 0; i < Suns.size();i++) {
                if (distance(Suns[i]->x + 20, Suns[i]->y+20, GetMouseX(), GetMouseY()) < 20) {
                    CurrentSun += Suns[i]->sungain;
                    Suns.erase(Suns.begin() + i);
                    i--;
                }
            }
            //Collecting Sun

            

        }
        //Mouse operation


        //Exit game if pressed E or any zombie passes the left line
        if (GetKey(olc::E).bPressed ) {
            gameEnd = true;
        }

        for (auto a : Zombies) {
            if (a->x <= 0) { gameEnd = true; }
        }

        if (gameEnd) {

            for (int i = 0; i < Zombies.size(); i++) {
                delete Zombies[i];
                Zombies.erase(Zombies.begin() + i);
                i--;
            }

            for (int i = 0; i < Peashooters.size(); i++) {
                delete Peashooters[i];
                Peashooters.erase(Peashooters.begin() + i);
                i--;
            }

            for (int i = 0; i < Sunflowers.size(); i++) {
                delete Sunflowers[i];
                Sunflowers.erase(Sunflowers.begin() + i);
                i--;
            }

            for (int i = 0; i < Suns.size(); i++) {
                delete Suns[i];
                Suns.erase(Suns.begin() + i);
                i--;
            }

            for (int i = 0; i < Seeds.size(); i++) {
                delete Seeds[i];
                Seeds.erase(Seeds.begin() + i);
                i--;
            }

            
            for (int i = 0; i < Tiles.size(); i++) {
                delete Tiles[i];
                Tiles.erase(Tiles.begin() + i);
                i--;
            }

            for (int i = 0; i < Cards.size(); i++) {
                delete Cards[i];
                Cards.erase(Cards.begin() + i);
                i--;
            }

            return true;
        }

        //Exit game if pressed E or any zombie passes the left line



       

        

        //Peashooter Draw
        for (auto i : Peashooters) {
            DrawSprite(i->x, i->y, peashooterSprite, 1);
        }
        //Peashooter Draw

        //Sunflower Draw
        for (auto i : Sunflowers) {
            DrawSprite(i->x, i->y, sunflowerSprite, 1);
        }
        //Sunflower Draw
        
        //Zombie Draw
        for (auto i : Zombies) {
            DrawSprite(i->x, i->y, zombieSprite, 1);
        }
        //Zombie Draw
        
        //Sun Draw
        for (auto i : Suns) {
            DrawSprite(i->x, i->y, sunSprite, 1);
        }
        //Sun Draw

        //Seed Draw
        for (auto i : Seeds) {
            DrawSprite(i->x, i->y, seedSprite, 1);
        }
        //Seed Draw

        return true;
    }

};






int main()
{
    PlantsGame demo;
    if (demo.Construct(300, 250, 3, 3))
        demo.Start();

    return 0;
}

**Comment by MumflrFumperdink** [comment]
You seem to have forgotten the

`#define OLC_PGE_APPLICATION`

at the top of the file.

**Comment by egetunadiken** [comment]
Now thanks a lot for that. YOU ARE THE MAN!!!!! I've managed to run my program. 

One more question: my photos have a problem when importing. 

zombieSprite = new olc::Sprite("Sprites/zombie1.png"); 

is this a syntax error or what could I be doing wrong? There seems to be stuff, but I can't see my png's.

**Comment by MumflrFumperdink** [comment]
For a quick fix, try using an absolute path (e.g. /Users/egetunadiken/.../Sprites/zombie1.png) instead of a relative path, that should work for coding it.

I think that for relative paths, you need to have it relative to the executable (not in the src directory, where I assume your "Sprites" folder is). Since, you're using Xcode, when you run it compiles a new executable every time and puts it in a different temporary folder.

**Comment by egetunadiken** [comment]
> For a quick fix, try using an absolute path (e.g. /Users/egetunadiken/.../Sprites/zombie1.png) instead of a relative path, that should work for coding it.
> 
> I think that for relative paths, you need to have it relative to the executable (not in the src directory, where I assume your "Sprites" folder is). Since, you're using Xcode, when you run it compiles a new executable every time and puts it in a different temporary folder.

Wow. You are a pro. Thanks a lot for all the help man! You made life better for me! I hope I'll get a good grade from this code. I'll be doing a few additions (we're basically creating plants vs zombies.) Do you have any suggestions for me? I'll first make my main.cpp into object oriented version and move on from that.

**Comment by MumflrFumperdink** [comment]
Other than making your project more OO with different files (which you said you would do), it all looks great. Good luck!

**Comment by egetunadiken** [comment]
This is going into a completely different discussion @MumflrFumperdink and I'm only asking because I know you're a pro. And maybe you'll be somewhat interested to check the code...

If you have time to check it and if you're interested, I'm posting some questions that jumbled my mind. I can't thank you enough for the help you've already given so you don't have to reply this...

1) What are the classes you'd suggest for me to have? I was thinking: main, board, sunflower, peashooter & zombie.
2) If there is a board class and a main class, how will they interact with each other, i.e. what should be in my main iyo?

**Comment by MumflrFumperdink** [comment]
Those look like good classes if you can picture the functionality and data differences between them. I suggest that a main class handle game logic, interactivity, etc. while the board class handles what is placed on the board, places things on the board, ways they can interact with the environment and each other, etc.
