### ISSUE TITLE
experimental/filesystem not found error

### ISSUE THREAD

**Issue by JupiterDoomsday** [MumflrFumperdink/olcPGEMac#17]
when I try to compile a script in Xcode using the header olcPixelGameEngine.h it keeps throwing a Lexical/ Preprocessor error that the 'experimental/filesystem' file is not found. The error seems to be caused in line 288 of the olcPixelGameEngine.h  where it can't grab the file.

**Comment by MumflrFumperdink** [comment]
What macOS version are you on? Also, try changing the <experimental/filesystem> to just <filesystem>, I think that might help.

**Comment by JupiterDoomsday** [comment]
> What macOS version are you on? Also, try changing the <experimental/filesystem> to just , I think that might help.

I'm using 10.13.6, also  what am I changing the <experimental/filesystem> to? just leave it blank or?

**Comment by JupiterDoomsday** [comment]
NVM just saw that the port needs tp be at LEAST  Mac 10.15! misread it as 10.5! my bad!
