### ISSUE TITLE
'png.h' file not found

### ISSUE THREAD

**Issue by amanns92** [MumflrFumperdink/olcPGEMac#24]
I installed  libpng over home-brew but my Xcode is still showing me that he can't find the png.h file.
for this I needed to add the library manually to my project. I made now a cmake project and added this lines.
link_directories("/opt/homebrew/lib")
include_directories("/opt/homebrew/include")
But now I get this error when I try to run the sample project:

: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/MyNes.dir/main.cpp.o -o MyNes -L/opt/homebrew/lib  && :
Undefined symbols for architecture arm64:
  "_CGLGetCurrentContext", referenced from:
      olc::Renderer_OGL10::CreateDevice(std::__1::vector<void*, std::__1::allocator<void*> >, bool, bool) in main.cpp.o

**Comment by amanns92** [comment]
I found the problem I also needed to install:
brew install glew
brew install freeglut
brew install libcarbon

It would be nice if this would be added to the Info.

**Comment by amanns92** [comment]
I found the problem I also needed to install:
brew install glew
brew install freeglut
brew install libcarbon

It would be nice if this would be added to the Info.

**Comment by Inaksa** [comment]
> I found the problem I also needed to install: brew install libcarbon
> 
> It would be nice if this would be added to the Info.

this library (libcarbon) is not available in Apple Silicon, so brew is unable to find even find it :(

**Comment by divygobi** [comment]
Same issue for me, has anyone found a workaround for Apple Silicon?

**Comment by amanns92** [comment]
I edited my comment. Since I had to reinstall my Mac I needed to set it up again and found a mistake in my post.

**Comment by divygobi** [comment]
I installed those and it still says file not found, are you on an Intel mac?

**Comment by amanns92** [comment]
no I am on apple silicon. What is the exact message you got?

**Comment by divygobi** [comment]
This is it:
../headers/../src/olcPixelGameEngine.h:4084:10: fatal error: 'png.h' file not found
#include <png.h>

I installed all the packages and it still doesn't work. What is the compile command you are using?
