### ISSUE TITLE
experimental/filesystem not found

### ISSUE THREAD

**Issue by SlashScreen** [MumflrFumperdink/olcPGEMac#4]
Using xcode 10 on macOS Mojave with clang-1001.0.46.4, on runtime, the compiler tells me "experimental/filesystem file not found" when just running the basic program. Is there any way to fix this? If there is, please explain in simple terms, I'm new to the world of c++.

(Also, fun little tidbit- it is apparent that the way apple makes their apps "dark mode" is by inverting all the colors, which makes the template logo look a bit silly.)
![Screenshot 2020-04-17 at 17 35 23](https://user-images.githubusercontent.com/12375239/79588827-c97c2580-80d4-11ea-957e-5282a2504f0d.png)

**Comment by MumflrFumperdink** [comment]
This seems to be a problem with your Xcode version. <filesystem> was added to Xcode in Xcode 11, so I would recommend upgrading Xcode to version 11 to see if it fixes the issue. If you try it out, tell me if it works!

Also, I did not know that about dark mode. Nice find!

**Comment by SlashScreen** [comment]
Ah, what a shame, Xcode 11 is for MacOS Catalina, and I have too many 32x apps to upgrade. Thanks anyway!

**Comment by SlashScreen** [comment]
Ah, what a shame, Xcode 11 is for MacOS Catalina, and I have too many 32x apps to upgrade. Thanks anyway!
